version: '3.8'

services:
  service1:
    build: ./service1
    container_name: service1
    ports:
      - "3000:3000"
    networks:
      - microservice-network

  service2:
    build: ./service2
    container_name: service2
    ports:
      - "3001:3001"
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge
