version: '3'
services:
  service1:
    build:
      context: .
      dockerfile: Dockerfile.service1
    ports:
      - "3001:3000"
    networks:
      - microservices-net

  service2:
    build:
      context: .
      dockerfile: Dockerfile.service2
    ports:
      - "3002:3000"
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge
